import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "../utils/Provider";
import { NavigationMenuDemo } from "./_components/Navbar";
import Footer from "./_components/Footer";
import Carousel from "./_components/Carousel";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen"}>
        <div className="grid grid-cols-1 grid-rows-layout h-full">
          <NavigationMenuDemo />
          <Provider>{children}</Provider>
         
          <Footer />
        </div>
      </body>
    </html>
  );
}
